### ISSUE TITLE
Clang 16 compile error

### ISSUE THREAD

**Issue by xakod** [falemagn/fameta-counter#2]
Hello, clang trunk or clang 16 cannot compile simple example https://godbolt.org/z/nYYeKM7b4

**Comment by falemagn** [comment]
Sorry for the delay in answering and thanks for the report.

It looks like a regression in clang, which takes way more time in compiling now than it did before, hence godbolt gives up.

You can test this by reducing the value of the `NUM_EXAMPLE` define at the top, to have less examples being compiled. None of those, taken alone, causes any issue, but all together cause clang to take way longer to compile than godbolt allows.

See it here: https://godbolt.org/z/GdrG1Ye3Y

It might be worth opening an issue with clang, perhaps?

**Comment by MarcTCruz** [comment]
It seems like an implementation problem instead of a Clang one. fameta-counter instatiates templates from N to previous N, so if     CX.next<1020>(),    CX.next<1030>() there are 10 template instatiations from the recursions(and one lookup) there while one could expect N to work just like a different argument so template could evaluate a new value in compile time.

The example fails on CLang due to the last test where the range of instatiations is huge to compute +1 to the value.
    C8.next<1001>(),
    C8.next<1030>(),

If it's changed from 1001 to 1020 Clang finishes compiling.

**Comment by falemagn** [comment]
> It seems like an implementation problem instead of a Clang one. fameta-counter instatiates templates from N to previous N, so if CX.next<1020>(), CX.next<1030>() there are at least 10 template recursions there while one could expect N to work just like a different argument so template could evaluate a new value in compile time.
> 
> The example fails on CLang due to the last test where the range of instatiations is huge to compute +1 to the value. C8.next<1001>(), C8.next<1030>(),
> 
> If it's changed from 1001 to 1020 Clang finishes compiling.

It'd be nice to come up with an implementation that requires less template instantiations, alas in the current implementation one needs to know what value, if any, CX.next<X-1> has in order to know the value CX.next<X>, and I can't imagine one that wouldn't, off the top of my head. 

Regardless, if it took less time with earlier clang versions, it's clear to me that there's a performance regression in clang in the first place.

**Comment by falemagn** [comment]
> It seems like an implementation problem instead of a Clang one. fameta-counter instatiates templates from N to previous N, so if CX.next<1020>(), CX.next<1030>() there are 10 template instatiations from the recursions(and one lookup) there while one could expect N to work just like a different argument so template could evaluate a new value in compile time.

Care to explain in detail how  you see this working differently?
 
Regardless, if clang didn't have problems with it in earlier versions but does now, it does look to me we're dealing with a performance regression.

**Comment by MarcTCruz** [comment]
> > It seems like an implementation problem instead of a Clang one. fameta-counter instatiates templates from N to previous N, so if CX.next<1020>(), CX.next<1030>() there are 10 template instatiations from the recursions(and one lookup) there while one could expect N to work just like a different argument so template could evaluate a new value in compile time.
> 
> Care to explain in detail how you see this working differently?
> 
> Regardless, if clang didn't have problems with it in earlier versions but does now, it does look to me we're dealing with a performance regression.

I'd expect the counter to be independet of the __LINE__, being it forward or backward recursion.

```
template<int Id>
struct counter {
    using tag = counter;

    struct generator {
        friend constexpr bool is_defined(tag)
        { return true; }
    };
    friend constexpr bool is_defined(tag);

    template<typename Tag = tag, bool = is_defined(Tag{})>
    static constexpr bool exists(int)
    { return true; }

    static constexpr auto exists(...)
    { return generator(), false; }
};

template<int LINE, int Id = int{}, bool Exists = counter<Id>::exists(Id)>
struct unique_id_impl {
    static constexpr auto value = unique_id_impl<LINE, Id + 1>::value;
};

template<int LINE, int Id>
struct unique_id_impl<LINE, Id, false> {
    static constexpr auto value = Id;
};

template<int LINE, int Id = int{}>
constexpr auto unique_id() {
    return unique_id_impl<LINE, Id>::value;
}

static_assert(unique_id<__LINE__>() == 0, "");
static_assert(unique_id<__LINE__>() == 1, "");

int main(){
    return 0;
}
```

In the above adaptation, the counter is independent from the variadic argument(LINE) which is just used to re-evaluate the template instead of being part of the lookup logic. This way, it's safer to implement some optimization(https://stackoverflow.com/a/45538120/475145) based on **is_defined** if in need of faster template instatiations.

For each incrementation it needs to iterate Steps=N where N = next_value, times instead of Steps=LINES_DIFFERENCE.
Your approach is good if next call is near previous one, when using a macro like __LINE__, but problematic with arbitrary differences(as it slow down the compilation in the shown way), also it depends on argument to be bigger.

**Comment by falemagn** [comment]
@Jihadist and @MarcTCruz, the current master should fix the issue. The API has been slightly changed, please have a look at the README.md file.
